default: --format html --out reports/results.html --format pretty --color --no-source --tags 'not @skip' --format json --out reports.json
<% common = "--format json --out reports.json --format pretty --color --no-source --tags 'not @skip'" %>
<% wip = "--tags @wip" %>
ff: <%= common %> BROWSER=firefox
headless: <%= common %> BROWSER=headless
dev: <%= common %> ENVIRONMENT=dev
wip: <%= wip %>
bs: <%= common %> PLATFORM=browserstack1
