default: --format html --out reports/results.html --format pretty --color --no-source --tags 'not @skip'
<% common = "--format json --out reports/reports.json --format pretty --color --no-source --tags 'not @skip'" %>
<% wip = "--format html --out reports/results.html --format pretty --color --no-source --tags 'not @skip' --tags @wip" %>
wip: <%= wip %>
ff: <%= common %> BROWSER=firefox
headless: <%= common %> BROWSER=headless
dev: <%= common %> ENVIRONMENT=dev
bs: <%= common %> PLATFORM=browserstack1
